//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyCard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaidShift
    {
        public int ShiftPaidId { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public double workedHours { get; set; }
        public int EmployeeId { get; set; }
        public string Month_Year { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
